version: "3"

includes:
  config: config/Taskfile.yml

tasks:
  submodule_update:
    desc: "Update Submodule"
    cmds:
      - git submodule update --init --recursive

  generate-code:
    desc: "Generate Code"
    vars:
      PYTHON_BIN_PATH: '{{.PYTHON_BIN_PATH }}'
      RES_CONFIG_PB: '{{.RES_CONFIG_PB }}'
      CONFIG_PROTOCOL_IMPORT_PATH: '{{.CONFIG_PROTOCOL_IMPORT_PATH }}'
      OUTPUT_DIR: '{{.OUTPUT_DIR }}'
    cmds:
      - task: config:generate-config-code
        vars:
          PROJECT_ROOT: '{{.TASKFILE_DIR}}'
          PYTHON_BIN_PATH: "{{.PYTHON_BIN_PATH}}"
          XRESLOADER_GEN_PYTHON: '{{.TASKFILE_DIR}}/third_party/xres-code-generator/xrescode-gen.py'
          RES_CONFIG_PB: "{{.RES_CONFIG_PB}}"
          CONFIG_PROTOCOL_IMPORT_PATH: "{{.CONFIG_PROTOCOL_IMPORT_PATH}}"
          OUTPUT_DIR: "{{.OUTPUT_DIR}}"

    dir: "{{.TASKFILE_DIR}}"