// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type access_data_algorithm_t byte

const (
	access_data_algorithm_tkHmacSha256 access_data_algorithm_t = 0
)

var EnumNamesaccess_data_algorithm_t = map[access_data_algorithm_t]string{
	access_data_algorithm_tkHmacSha256: "kHmacSha256",
}

var EnumValuesaccess_data_algorithm_t = map[string]access_data_algorithm_t{
	"kHmacSha256": access_data_algorithm_tkHmacSha256,
}

func (v access_data_algorithm_t) String() string {
	if s, ok := EnumNamesaccess_data_algorithm_t[v]; ok {
		return s
	}
	return "access_data_algorithm_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
