// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// message
type client_message struct {
	_tab flatbuffers.Table
}

const client_messageIdentifier = "ATGW"

func GetRootAsclient_message(buf []byte, offset flatbuffers.UOffsetT) *client_message {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &client_message{}
	x.Init(buf, n+offset)
	return x
}

func Finishclient_messageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(client_messageIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func client_messageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, client_messageIdentifier)
}

func GetSizePrefixedRootAsclient_message(buf []byte, offset flatbuffers.UOffsetT) *client_message {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &client_message{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedclient_messageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(client_messageIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedclient_messageBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, client_messageIdentifier)
}

func (rcv *client_message) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *client_message) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *client_message) Head(obj *client_message_head) *client_message_head {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(client_message_head)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *client_message) BodyType() client_message_body {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return client_message_body(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *client_message) MutateBodyType(n client_message_body) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *client_message) Body(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func client_messageStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func client_messageAddHead(builder *flatbuffers.Builder, head flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(head), 0)
}
func client_messageAddBodyType(builder *flatbuffers.Builder, bodyType client_message_body) {
	builder.PrependByteSlot(1, byte(bodyType), 0)
}
func client_messageAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(body), 0)
}
func client_messageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
