// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type client_message_body byte

const (
	client_message_bodyNONE              client_message_body = 0
	client_message_bodycs_body_post      client_message_body = 1
	client_message_bodycs_body_kickoff   client_message_body = 2
	client_message_bodycs_body_ping      client_message_body = 3
	client_message_bodycs_body_handshake client_message_body = 4
	client_message_bodycs_body_confirm   client_message_body = 5
)

var EnumNamesclient_message_body = map[client_message_body]string{
	client_message_bodyNONE:              "NONE",
	client_message_bodycs_body_post:      "cs_body_post",
	client_message_bodycs_body_kickoff:   "cs_body_kickoff",
	client_message_bodycs_body_ping:      "cs_body_ping",
	client_message_bodycs_body_handshake: "cs_body_handshake",
	client_message_bodycs_body_confirm:   "cs_body_confirm",
}

var EnumValuesclient_message_body = map[string]client_message_body{
	"NONE":              client_message_bodyNONE,
	"cs_body_post":      client_message_bodycs_body_post,
	"cs_body_kickoff":   client_message_bodycs_body_kickoff,
	"cs_body_ping":      client_message_bodycs_body_ping,
	"cs_body_handshake": client_message_bodycs_body_handshake,
	"cs_body_confirm":   client_message_bodycs_body_confirm,
}

func (v client_message_body) String() string {
	if s, ok := EnumNamesclient_message_body[v]; ok {
		return s
	}
	return "client_message_body(" + strconv.FormatInt(int64(v), 10) + ")"
}
