// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type client_message_type_t byte

const (
	client_message_type_tkUnknown   client_message_type_t = 0
	client_message_type_tkPost      client_message_type_t = 1
	client_message_type_tkHandshake client_message_type_t = 2
	client_message_type_tkPing      client_message_type_t = 3
	client_message_type_tkPong      client_message_type_t = 4
	client_message_type_tkKickoff   client_message_type_t = 5
	client_message_type_tkConfirm   client_message_type_t = 6
)

var EnumNamesclient_message_type_t = map[client_message_type_t]string{
	client_message_type_tkUnknown:   "kUnknown",
	client_message_type_tkPost:      "kPost",
	client_message_type_tkHandshake: "kHandshake",
	client_message_type_tkPing:      "kPing",
	client_message_type_tkPong:      "kPong",
	client_message_type_tkKickoff:   "kKickoff",
	client_message_type_tkConfirm:   "kConfirm",
}

var EnumValuesclient_message_type_t = map[string]client_message_type_t{
	"kUnknown":   client_message_type_tkUnknown,
	"kPost":      client_message_type_tkPost,
	"kHandshake": client_message_type_tkHandshake,
	"kPing":      client_message_type_tkPing,
	"kPong":      client_message_type_tkPong,
	"kKickoff":   client_message_type_tkKickoff,
	"kConfirm":   client_message_type_tkConfirm,
}

func (v client_message_type_t) String() string {
	if s, ok := EnumNamesclient_message_type_t[v]; ok {
		return s
	}
	return "client_message_type_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
