// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type client_message_head struct {
	_tab flatbuffers.Table
}

func GetRootAsclient_message_head(buf []byte, offset flatbuffers.UOffsetT) *client_message_head {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &client_message_head{}
	x.Init(buf, n+offset)
	return x
}

func Finishclient_message_headBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsclient_message_head(buf []byte, offset flatbuffers.UOffsetT) *client_message_head {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &client_message_head{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedclient_message_headBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *client_message_head) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *client_message_head) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *client_message_head) Type() client_message_type_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return client_message_type_t(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *client_message_head) MutateType(n client_message_type_t) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *client_message_head) Sequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *client_message_head) MutateSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func client_message_headStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func client_message_headAddType(builder *flatbuffers.Builder, type_ client_message_type_t) {
	builder.PrependByteSlot(0, byte(type_), 0)
}
func client_message_headAddSequence(builder *flatbuffers.Builder, sequence uint64) {
	builder.PrependUint64Slot(1, sequence, 0)
}
func client_message_headEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
