// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type compression_algorithm_t byte

const (
	compression_algorithm_tkNone   compression_algorithm_t = 0
	compression_algorithm_tkZstd   compression_algorithm_t = 10
	compression_algorithm_tkLz4    compression_algorithm_t = 20
	compression_algorithm_tkSnappy compression_algorithm_t = 30
	compression_algorithm_tkZlib   compression_algorithm_t = 40
)

var EnumNamescompression_algorithm_t = map[compression_algorithm_t]string{
	compression_algorithm_tkNone:   "kNone",
	compression_algorithm_tkZstd:   "kZstd",
	compression_algorithm_tkLz4:    "kLz4",
	compression_algorithm_tkSnappy: "kSnappy",
	compression_algorithm_tkZlib:   "kZlib",
}

var EnumValuescompression_algorithm_t = map[string]compression_algorithm_t{
	"kNone":   compression_algorithm_tkNone,
	"kZstd":   compression_algorithm_tkZstd,
	"kLz4":    compression_algorithm_tkLz4,
	"kSnappy": compression_algorithm_tkSnappy,
	"kZlib":   compression_algorithm_tkZlib,
}

func (v compression_algorithm_t) String() string {
	if s, ok := EnumNamescompression_algorithm_t[v]; ok {
		return s
	}
	return "compression_algorithm_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
