// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type compression_level_t byte

const (
	compression_level_tkDefault   compression_level_t = 0
	compression_level_tkStorage   compression_level_t = 10
	compression_level_tkFast      compression_level_t = 20
	compression_level_tkLowCpu    compression_level_t = 30
	compression_level_tkBalanced  compression_level_t = 40
	compression_level_tkHighRatio compression_level_t = 50
	compression_level_tkMaxRatio  compression_level_t = 60
)

var EnumNamescompression_level_t = map[compression_level_t]string{
	compression_level_tkDefault:   "kDefault",
	compression_level_tkStorage:   "kStorage",
	compression_level_tkFast:      "kFast",
	compression_level_tkLowCpu:    "kLowCpu",
	compression_level_tkBalanced:  "kBalanced",
	compression_level_tkHighRatio: "kHighRatio",
	compression_level_tkMaxRatio:  "kMaxRatio",
}

var EnumValuescompression_level_t = map[string]compression_level_t{
	"kDefault":   compression_level_tkDefault,
	"kStorage":   compression_level_tkStorage,
	"kFast":      compression_level_tkFast,
	"kLowCpu":    compression_level_tkLowCpu,
	"kBalanced":  compression_level_tkBalanced,
	"kHighRatio": compression_level_tkHighRatio,
	"kMaxRatio":  compression_level_tkMaxRatio,
}

func (v compression_level_t) String() string {
	if s, ok := EnumNamescompression_level_t[v]; ok {
		return s
	}
	return "compression_level_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
