// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type crypto_algorithm_t byte

const (
	crypto_algorithm_tkNone                  crypto_algorithm_t = 0
	crypto_algorithm_tkXxtea                 crypto_algorithm_t = 1
	crypto_algorithm_tkAes128Cbc             crypto_algorithm_t = 11
	crypto_algorithm_tkAes192Cbc             crypto_algorithm_t = 12
	crypto_algorithm_tkAes256Cbc             crypto_algorithm_t = 13
	crypto_algorithm_tkAes128Gcm             crypto_algorithm_t = 14
	crypto_algorithm_tkAes192Gcm             crypto_algorithm_t = 15
	crypto_algorithm_tkAes256Gcm             crypto_algorithm_t = 16
	crypto_algorithm_tkChacha20              crypto_algorithm_t = 31
	crypto_algorithm_tkChacha20Poly1305Ietf  crypto_algorithm_t = 32
	crypto_algorithm_tkXchacha20Poly1305Ietf crypto_algorithm_t = 33
)

var EnumNamescrypto_algorithm_t = map[crypto_algorithm_t]string{
	crypto_algorithm_tkNone:                  "kNone",
	crypto_algorithm_tkXxtea:                 "kXxtea",
	crypto_algorithm_tkAes128Cbc:             "kAes128Cbc",
	crypto_algorithm_tkAes192Cbc:             "kAes192Cbc",
	crypto_algorithm_tkAes256Cbc:             "kAes256Cbc",
	crypto_algorithm_tkAes128Gcm:             "kAes128Gcm",
	crypto_algorithm_tkAes192Gcm:             "kAes192Gcm",
	crypto_algorithm_tkAes256Gcm:             "kAes256Gcm",
	crypto_algorithm_tkChacha20:              "kChacha20",
	crypto_algorithm_tkChacha20Poly1305Ietf:  "kChacha20Poly1305Ietf",
	crypto_algorithm_tkXchacha20Poly1305Ietf: "kXchacha20Poly1305Ietf",
}

var EnumValuescrypto_algorithm_t = map[string]crypto_algorithm_t{
	"kNone":                  crypto_algorithm_tkNone,
	"kXxtea":                 crypto_algorithm_tkXxtea,
	"kAes128Cbc":             crypto_algorithm_tkAes128Cbc,
	"kAes192Cbc":             crypto_algorithm_tkAes192Cbc,
	"kAes256Cbc":             crypto_algorithm_tkAes256Cbc,
	"kAes128Gcm":             crypto_algorithm_tkAes128Gcm,
	"kAes192Gcm":             crypto_algorithm_tkAes192Gcm,
	"kAes256Gcm":             crypto_algorithm_tkAes256Gcm,
	"kChacha20":              crypto_algorithm_tkChacha20,
	"kChacha20Poly1305Ietf":  crypto_algorithm_tkChacha20Poly1305Ietf,
	"kXchacha20Poly1305Ietf": crypto_algorithm_tkXchacha20Poly1305Ietf,
}

func (v crypto_algorithm_t) String() string {
	if s, ok := EnumNamescrypto_algorithm_t[v]; ok {
		return s
	}
	return "crypto_algorithm_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
