// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_confirm struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_confirm(buf []byte, offset flatbuffers.UOffsetT) *cs_body_confirm {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_confirm{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_confirmBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_confirm(buf []byte, offset flatbuffers.UOffsetT) *cs_body_confirm {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_confirm{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_confirmBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_confirm) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_confirm) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_confirm) SessionId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_confirm) MutateSessionId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *cs_body_confirm) HandshakeSequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_confirm) MutateHandshakeSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func cs_body_confirmStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func cs_body_confirmAddSessionId(builder *flatbuffers.Builder, sessionId uint64) {
	builder.PrependUint64Slot(0, sessionId, 0)
}
func cs_body_confirmAddHandshakeSequence(builder *flatbuffers.Builder, handshakeSequence uint64) {
	builder.PrependUint64Slot(1, handshakeSequence, 0)
}
func cs_body_confirmEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
