// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_ping struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_ping(buf []byte, offset flatbuffers.UOffsetT) *cs_body_ping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_ping{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_pingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_ping(buf []byte, offset flatbuffers.UOffsetT) *cs_body_ping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_ping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_pingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_ping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_ping) Table() flatbuffers.Table {
	return rcv._tab
}

/// the time when start ping
func (rcv *cs_body_ping) Timepoint() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

/// the time when start ping
func (rcv *cs_body_ping) MutateTimepoint(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func cs_body_pingStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func cs_body_pingAddTimepoint(builder *flatbuffers.Builder, timepoint int64) {
	builder.PrependInt64Slot(0, timepoint, 0)
}
func cs_body_pingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
