// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_post_crypto struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_post_crypto(buf []byte, offset flatbuffers.UOffsetT) *cs_body_post_crypto {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_post_crypto{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_post_cryptoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_post_crypto(buf []byte, offset flatbuffers.UOffsetT) *cs_body_post_crypto {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_post_crypto{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_post_cryptoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_post_crypto) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_post_crypto) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_post_crypto) Algorithm() crypto_algorithm_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return crypto_algorithm_t(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *cs_body_post_crypto) MutateAlgorithm(n crypto_algorithm_t) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *cs_body_post_crypto) Iv(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *cs_body_post_crypto) IvLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_post_crypto) MutateIv(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *cs_body_post_crypto) Aad(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *cs_body_post_crypto) AadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_post_crypto) MutateAad(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func cs_body_post_cryptoStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func cs_body_post_cryptoAddAlgorithm(builder *flatbuffers.Builder, algorithm crypto_algorithm_t) {
	builder.PrependByteSlot(0, byte(algorithm), 0)
}
func cs_body_post_cryptoAddIv(builder *flatbuffers.Builder, iv flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(iv), 0)
}
func cs_body_post_cryptoStartIvVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_post_cryptoAddAad(builder *flatbuffers.Builder, aad flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(aad), 0)
}
func cs_body_post_cryptoStartAadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_post_cryptoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
