// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_kickoff struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_kickoff(buf []byte, offset flatbuffers.UOffsetT) *cs_body_kickoff {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_kickoff{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_kickoffBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_kickoff(buf []byte, offset flatbuffers.UOffsetT) *cs_body_kickoff {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_kickoff{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_kickoffBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_kickoff) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_kickoff) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_kickoff) Reason() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_kickoff) MutateReason(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *cs_body_kickoff) SubReason() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_kickoff) MutateSubReason(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *cs_body_kickoff) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func cs_body_kickoffStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func cs_body_kickoffAddReason(builder *flatbuffers.Builder, reason int32) {
	builder.PrependInt32Slot(0, reason, 0)
}
func cs_body_kickoffAddSubReason(builder *flatbuffers.Builder, subReason int32) {
	builder.PrependInt32Slot(1, subReason, 0)
}
func cs_body_kickoffAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func cs_body_kickoffEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
