// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_handshake_access_data struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_handshake_access_data(buf []byte, offset flatbuffers.UOffsetT) *cs_body_handshake_access_data {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_handshake_access_data{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_handshake_access_dataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_handshake_access_data(buf []byte, offset flatbuffers.UOffsetT) *cs_body_handshake_access_data {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_handshake_access_data{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_handshake_access_dataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_handshake_access_data) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_handshake_access_data) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_handshake_access_data) Algorithm() access_data_algorithm_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return access_data_algorithm_t(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *cs_body_handshake_access_data) MutateAlgorithm(n access_data_algorithm_t) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *cs_body_handshake_access_data) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_handshake_access_data) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *cs_body_handshake_access_data) Nonce1() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_handshake_access_data) MutateNonce1(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *cs_body_handshake_access_data) Nonce2() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_handshake_access_data) MutateNonce2(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *cs_body_handshake_access_data) Signature(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *cs_body_handshake_access_data) SignatureLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake_access_data) MutateSignature(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func cs_body_handshake_access_dataStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func cs_body_handshake_access_dataAddAlgorithm(builder *flatbuffers.Builder, algorithm access_data_algorithm_t) {
	builder.PrependByteSlot(0, byte(algorithm), 0)
}
func cs_body_handshake_access_dataAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(1, timestamp, 0)
}
func cs_body_handshake_access_dataAddNonce1(builder *flatbuffers.Builder, nonce1 uint64) {
	builder.PrependUint64Slot(2, nonce1, 0)
}
func cs_body_handshake_access_dataAddNonce2(builder *flatbuffers.Builder, nonce2 uint64) {
	builder.PrependUint64Slot(3, nonce2, 0)
}
func cs_body_handshake_access_dataAddSignature(builder *flatbuffers.Builder, signature flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(signature), 0)
}
func cs_body_handshake_access_dataStartSignatureVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_handshake_access_dataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
