// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_post_compression struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_post_compression(buf []byte, offset flatbuffers.UOffsetT) *cs_body_post_compression {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_post_compression{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_post_compressionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_post_compression(buf []byte, offset flatbuffers.UOffsetT) *cs_body_post_compression {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_post_compression{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_post_compressionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_post_compression) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_post_compression) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_post_compression) Type() compression_algorithm_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return compression_algorithm_t(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *cs_body_post_compression) MutateType(n compression_algorithm_t) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *cs_body_post_compression) OriginalSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_post_compression) MutateOriginalSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func cs_body_post_compressionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func cs_body_post_compressionAddType(builder *flatbuffers.Builder, type_ compression_algorithm_t) {
	builder.PrependByteSlot(0, byte(type_), 0)
}
func cs_body_post_compressionAddOriginalSize(builder *flatbuffers.Builder, originalSize uint64) {
	builder.PrependUint64Slot(1, originalSize, 0)
}
func cs_body_post_compressionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
