// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type cs_body_post struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_post(buf []byte, offset flatbuffers.UOffsetT) *cs_body_post {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_post{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_postBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_post(buf []byte, offset flatbuffers.UOffsetT) *cs_body_post {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_post{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_postBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_post) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_post) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_post) Crypto(obj *cs_body_post_crypto) *cs_body_post_crypto {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cs_body_post_crypto)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *cs_body_post) Compression(obj *cs_body_post_compression) *cs_body_post_compression {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cs_body_post_compression)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// body size without padding
func (rcv *cs_body_post) Length() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// body size without padding
func (rcv *cs_body_post) MutateLength(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *cs_body_post) Data(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *cs_body_post) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_post) MutateData(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func cs_body_postStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func cs_body_postAddCrypto(builder *flatbuffers.Builder, crypto flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(crypto), 0)
}
func cs_body_postAddCompression(builder *flatbuffers.Builder, compression flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(compression), 0)
}
func cs_body_postAddLength(builder *flatbuffers.Builder, length uint64) {
	builder.PrependUint64Slot(2, length, 0)
}
func cs_body_postAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(data), 0)
}
func cs_body_postStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_postEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
