// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Handshake body for the 2-message key exchange (like libatbus register req/rsp).
///
/// kKeyExchangeReq (Client -> Server):
///   - key_exchange: selected ECDH curve (must not be kNone for encrypted sessions)
///   - algorithms[]: all cipher algorithms supported by the client
///   - kdf_type[]: all KDF types supported by the client
///   - public_key: client's ECDH ephemeral public key
///   - access_data: HMAC-SHA256 authentication
///   - compression_algorithm[]: all compression algorithms supported by client
///
/// kKeyExchangeRsp (Server -> Client):
///   - session_id: newly assigned session ID
///   - key_exchange: confirmed ECDH curve (echoed from req)
///   - algorithms[]: single selected cipher algorithm
///   - kdf_type[]: single selected KDF type
///   - public_key: server's ECDH ephemeral public key
///   - access_data: HMAC-SHA256 authentication
///   - iv_size/tag_size: negotiated IV and tag sizes
///   - compression_algorithm[]: single selected compression algorithm
///   - max_post_message_size: maximum post message size in bytes
///
/// After both sides have each other's public key, they derive:
///   shared_secret = ECDH(my_private, peer_public)
///   key_material = HKDF(SHA256, shared_secret, nil, nil, key_size + iv_size)
///   KEY = key_material[0..key_size-1]
///   IV  = key_material[key_size..key_size+iv_size-1]
type cs_body_handshake struct {
	_tab flatbuffers.Table
}

func GetRootAscs_body_handshake(buf []byte, offset flatbuffers.UOffsetT) *cs_body_handshake {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &cs_body_handshake{}
	x.Init(buf, n+offset)
	return x
}

func Finishcs_body_handshakeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAscs_body_handshake(buf []byte, offset flatbuffers.UOffsetT) *cs_body_handshake {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &cs_body_handshake{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedcs_body_handshakeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *cs_body_handshake) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *cs_body_handshake) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *cs_body_handshake) SessionId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_handshake) MutateSessionId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *cs_body_handshake) Step() handshake_step_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return handshake_step_t(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *cs_body_handshake) MutateStep(n handshake_step_t) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *cs_body_handshake) KeyExchange() key_exchange_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return key_exchange_t(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *cs_body_handshake) MutateKeyExchange(n key_exchange_t) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *cs_body_handshake) KdfType(j int) kdf_algorithm_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return kdf_algorithm_t(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *cs_body_handshake) KdfTypeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake) KdfTypeBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *cs_body_handshake) MutateKdfType(j int, n kdf_algorithm_t) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

func (rcv *cs_body_handshake) Algorithms(j int) crypto_algorithm_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return crypto_algorithm_t(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *cs_body_handshake) AlgorithmsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake) AlgorithmsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *cs_body_handshake) MutateAlgorithms(j int, n crypto_algorithm_t) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

func (rcv *cs_body_handshake) AccessData(obj *cs_body_handshake_access_data, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *cs_body_handshake) AccessDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake) PublicKey(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *cs_body_handshake) PublicKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake) MutatePublicKey(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *cs_body_handshake) InitializeCrypto(obj *cs_body_post_crypto) *cs_body_post_crypto {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cs_body_post_crypto)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *cs_body_handshake) CompressionAlgorithm(j int) compression_algorithm_t {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return compression_algorithm_t(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *cs_body_handshake) CompressionAlgorithmLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake) CompressionAlgorithmBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *cs_body_handshake) MutateCompressionAlgorithm(j int, n compression_algorithm_t) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

func (rcv *cs_body_handshake) MaxPostMessageSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_handshake) MutateMaxPostMessageSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func (rcv *cs_body_handshake) SessionToken(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *cs_body_handshake) SessionTokenLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *cs_body_handshake) MutateSessionToken(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *cs_body_handshake) HandshakeSequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *cs_body_handshake) MutateHandshakeSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func cs_body_handshakeStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func cs_body_handshakeAddSessionId(builder *flatbuffers.Builder, sessionId uint64) {
	builder.PrependUint64Slot(0, sessionId, 0)
}
func cs_body_handshakeAddStep(builder *flatbuffers.Builder, step handshake_step_t) {
	builder.PrependByteSlot(1, byte(step), 0)
}
func cs_body_handshakeAddKeyExchange(builder *flatbuffers.Builder, keyExchange key_exchange_t) {
	builder.PrependByteSlot(2, byte(keyExchange), 0)
}
func cs_body_handshakeAddKdfType(builder *flatbuffers.Builder, kdfType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(kdfType), 0)
}
func cs_body_handshakeStartKdfTypeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_handshakeAddAlgorithms(builder *flatbuffers.Builder, algorithms flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(algorithms), 0)
}
func cs_body_handshakeStartAlgorithmsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_handshakeAddAccessData(builder *flatbuffers.Builder, accessData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(accessData), 0)
}
func cs_body_handshakeStartAccessDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func cs_body_handshakeAddPublicKey(builder *flatbuffers.Builder, publicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(publicKey), 0)
}
func cs_body_handshakeStartPublicKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_handshakeAddInitializeCrypto(builder *flatbuffers.Builder, initializeCrypto flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(initializeCrypto), 0)
}
func cs_body_handshakeAddCompressionAlgorithm(builder *flatbuffers.Builder, compressionAlgorithm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(compressionAlgorithm), 0)
}
func cs_body_handshakeStartCompressionAlgorithmVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_handshakeAddMaxPostMessageSize(builder *flatbuffers.Builder, maxPostMessageSize uint64) {
	builder.PrependUint64Slot(9, maxPostMessageSize, 0)
}
func cs_body_handshakeAddSessionToken(builder *flatbuffers.Builder, sessionToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(sessionToken), 0)
}
func cs_body_handshakeStartSessionTokenVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func cs_body_handshakeAddHandshakeSequence(builder *flatbuffers.Builder, handshakeSequence uint64) {
	builder.PrependUint64Slot(11, handshakeSequence, 0)
}
func cs_body_handshakeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
