// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type error_code_t int32

const (
	error_code_tkRefuseReconnect error_code_t = -1005
	error_code_tkSessionExpired  error_code_t = -1004
	error_code_tkBusy            error_code_t = -1003
	error_code_tkHandshake       error_code_t = -1002
	error_code_tkFirstIdel       error_code_t = -1001
	error_code_tkSuccess         error_code_t = 0
)

var EnumNameserror_code_t = map[error_code_t]string{
	error_code_tkRefuseReconnect: "kRefuseReconnect",
	error_code_tkSessionExpired:  "kSessionExpired",
	error_code_tkBusy:            "kBusy",
	error_code_tkHandshake:       "kHandshake",
	error_code_tkFirstIdel:       "kFirstIdel",
	error_code_tkSuccess:         "kSuccess",
}

var EnumValueserror_code_t = map[string]error_code_t{
	"kRefuseReconnect": error_code_tkRefuseReconnect,
	"kSessionExpired":  error_code_tkSessionExpired,
	"kBusy":            error_code_tkBusy,
	"kHandshake":       error_code_tkHandshake,
	"kFirstIdel":       error_code_tkFirstIdel,
	"kSuccess":         error_code_tkSuccess,
}

func (v error_code_t) String() string {
	if s, ok := EnumNameserror_code_t[v]; ok {
		return s
	}
	return "error_code_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
