// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type handshake_step_t byte

const (
	handshake_step_tkKeyExchangeReq handshake_step_t = 0
	handshake_step_tkKeyExchangeRsp handshake_step_t = 1
	handshake_step_tkReconnectReq   handshake_step_t = 11
	handshake_step_tkReconnectRsp   handshake_step_t = 12
)

var EnumNameshandshake_step_t = map[handshake_step_t]string{
	handshake_step_tkKeyExchangeReq: "kKeyExchangeReq",
	handshake_step_tkKeyExchangeRsp: "kKeyExchangeRsp",
	handshake_step_tkReconnectReq:   "kReconnectReq",
	handshake_step_tkReconnectRsp:   "kReconnectRsp",
}

var EnumValueshandshake_step_t = map[string]handshake_step_t{
	"kKeyExchangeReq": handshake_step_tkKeyExchangeReq,
	"kKeyExchangeRsp": handshake_step_tkKeyExchangeRsp,
	"kReconnectReq":   handshake_step_tkReconnectReq,
	"kReconnectRsp":   handshake_step_tkReconnectRsp,
}

func (v handshake_step_t) String() string {
	if s, ok := EnumNameshandshake_step_t[v]; ok {
		return s
	}
	return "handshake_step_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
