// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type kdf_algorithm_t byte

const (
	kdf_algorithm_tkHkdfSha256 kdf_algorithm_t = 0
)

var EnumNameskdf_algorithm_t = map[kdf_algorithm_t]string{
	kdf_algorithm_tkHkdfSha256: "kHkdfSha256",
}

var EnumValueskdf_algorithm_t = map[string]kdf_algorithm_t{
	"kHkdfSha256": kdf_algorithm_tkHkdfSha256,
}

func (v kdf_algorithm_t) String() string {
	if s, ok := EnumNameskdf_algorithm_t[v]; ok {
		return s
	}
	return "kdf_algorithm_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
