// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package v2

import "strconv"

type key_exchange_t byte

const (
	key_exchange_tkNone      key_exchange_t = 0
	key_exchange_tkX25519    key_exchange_t = 1
	key_exchange_tkSecp256r1 key_exchange_t = 2
	key_exchange_tkSecp384r1 key_exchange_t = 3
	key_exchange_tkSecp521r1 key_exchange_t = 4
)

var EnumNameskey_exchange_t = map[key_exchange_t]string{
	key_exchange_tkNone:      "kNone",
	key_exchange_tkX25519:    "kX25519",
	key_exchange_tkSecp256r1: "kSecp256r1",
	key_exchange_tkSecp384r1: "kSecp384r1",
	key_exchange_tkSecp521r1: "kSecp521r1",
}

var EnumValueskey_exchange_t = map[string]key_exchange_t{
	"kNone":      key_exchange_tkNone,
	"kX25519":    key_exchange_tkX25519,
	"kSecp256r1": key_exchange_tkSecp256r1,
	"kSecp384r1": key_exchange_tkSecp384r1,
	"kSecp521r1": key_exchange_tkSecp521r1,
}

func (v key_exchange_t) String() string {
	if s, ok := EnumNameskey_exchange_t[v]; ok {
		return s
	}
	return "key_exchange_t(" + strconv.FormatInt(int64(v), 10) + ")"
}
